spring:
  application:
    name: product
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: '1205'
    initialize: true
  server:
    port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
