name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build all microservices
        run: |
          # Build each microservice
          for dir in api-gateway cart-service product service-registry user; do
            echo "Building $dir"
            cd $dir
            mvn clean install
            cd ..
          done